### ISSUE TITLE
align items to centre with proper spacing with each questions

### ISSUE THREAD

**Issue by Saranshgaurav** [Saranshgaurav/surveyform#1]

**Comment by ghost** [comment]
i think i can solve this so can you please assign this to me

**Comment by sayan404** [comment]
I want to work in this issue please assign me this issue @Saranshgaurav

**Comment by Saranshgaurav** [comment]
ok you both go ahead

**Comment by Saranshgaurav** [comment]
i will select on my choice

**Comment by Saranshgaurav** [comment]
go ahead both of you
